In [1]:
import os
import pandas as pd

In [2]:
shots_df = pd.read_csv("Resources/shot_logs.csv")

In [3]:
shots_df.head()

,GAME_ID,MATCHUP,LOCATION,W,FINAL_MARGIN,SHOT_NUMBER,PERIOD,GAME_CLOCK,SHOT_CLOCK,DRIBBLES,...,SHOT_DIST,PTS_TYPE,SHOT_RESULT,CLOSEST_DEFENDER,CLOSEST_DEFENDER_PLAYER_ID,CLOSE_DEF_DIST,FGM,PTS,player_name,player_id
0,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,1,1,1:09,10.8,2,...,7.7,2,made,"Anderson, Alan",101187,1.3,1,2,brian roberts,203148
1,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,2,1,0:14,3.4,0,...,28.2,3,missed,"Bogdanovic, Bojan",202711,6.1,0,0,brian roberts,203148
2,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,3,1,0:00,NaN,3,...,10.1,2,missed,"Bogdanovic, Bojan",202711,0.9,0,0,brian roberts,203148
3,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,4,2,11:47,10.3,2,...,17.2,2,missed,"Brown, Markel",203900,3.4,0,0,brian roberts,203148
4,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,5,2,10:34,10.9,2,...,3.7,2,missed,"Young, Thaddeus",201152,1.1,0,0,brian roberts,203148

In [101]:
df = shots_df.drop(columns=["GAME_ID", "LOCATION", "W",
               "FINAL_MARGIN", "PERIOD", 
               "CLOSEST_DEFENDER_PLAYER_ID",
               "FGM","PTS","player_id"])

In [102]:
df2 = df.rename(columns={"player_name":"Player", "SHOT_NUMBER": "Shot Number", 
                   "GAME_CLOCK": "Game Clock", "SHOT_CLOCK": "Shot Clock",
                  "DRIBBLES": "Dribbles", "TOUCH_TIME": "Touch Time",
                  "SHOT_DIST": "Shot Distance", "PTS_TYPE": "Shot Type",
                  "SHOT_RESULT": "Shot Result", "CLOSEST_DEFENDER": "Closest Defender",
                  "CLOSE_DEF_DIST": "Closest Defender Distance"})
new_df = df2[['Player', 'Shot Number', 'Closest Defender',
                'Closest Defender Distance','Game Clock','Shot Clock',
                'Dribbles', 'Touch Time', 'Shot Distance', 'Shot Type',
                'Shot Result']]

new_df.head()

,Player,Shot Number,Closest Defender,Closest Defender Distance,Game Clock,Shot Clock,Dribbles,Touch Time,Shot Distance,Shot Type,Shot Result
0,brian roberts,1,"Anderson, Alan",1.3,1:09,10.8,2,1.9,7.7,2,made
1,brian roberts,2,"Bogdanovic, Bojan",6.1,0:14,3.4,0,0.8,28.2,3,missed
2,brian roberts,3,"Bogdanovic, Bojan",0.9,0:00,NaN,3,2.7,10.1,2,missed
3,brian roberts,4,"Brown, Markel",3.4,11:47,10.3,2,1.9,17.2,2,missed
4,brian roberts,5,"Young, Thaddeus",1.1,10:34,10.9,2,2.7,3.7,2,missed

In [103]:
new_df['Player']= new_df['Player'].str.title()
new_df.head()

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Player,Shot Number,Closest Defender,Closest Defender Distance,Game Clock,Shot Clock,Dribbles,Touch Time,Shot Distance,Shot Type,Shot Result
0,Brian Roberts,1,"Anderson, Alan",1.3,1:09,10.8,2,1.9,7.7,2,made
1,Brian Roberts,2,"Bogdanovic, Bojan",6.1,0:14,3.4,0,0.8,28.2,3,missed
2,Brian Roberts,3,"Bogdanovic, Bojan",0.9,0:00,NaN,3,2.7,10.1,2,missed
3,Brian Roberts,4,"Brown, Markel",3.4,11:47,10.3,2,1.9,17.2,2,missed
4,Brian Roberts,5,"Young, Thaddeus",1.1,10:34,10.9,2,2.7,3.7,2,missed

In [104]:
new_df.head()

,Player,Shot Number,Closest Defender,Closest Defender Distance,Game Clock,Shot Clock,Dribbles,Touch Time,Shot Distance,Shot Type,Shot Result
0,Brian Roberts,1,"Anderson, Alan",1.3,1:09,10.8,2,1.9,7.7,2,made
1,Brian Roberts,2,"Bogdanovic, Bojan",6.1,0:14,3.4,0,0.8,28.2,3,missed
2,Brian Roberts,3,"Bogdanovic, Bojan",0.9,0:00,NaN,3,2.7,10.1,2,missed
3,Brian Roberts,4,"Brown, Markel",3.4,11:47,10.3,2,1.9,17.2,2,missed
4,Brian Roberts,5,"Young, Thaddeus",1.1,10:34,10.9,2,2.7,3.7,2,missed

In [115]:
def reverse_name(name):
    try:
        split_name = name.split(",")
        last_name = split_name[0]
        first_name = split_name[1]
        return first_name + " " + last_name
    except:
        print(split_name)

new_df['Closest Defender'] = new_df['Closest Defender'].apply(reverse_name)

['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']
['Nene']

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [116]:
new_df.head()

,Player,Shot Number,Closest Defender,Closest Defender Distance,Game Clock,Shot Clock,Dribbles,Touch Time,Shot Distance,Shot Type,Shot Result
0,Brian Roberts,1,Alan Anderson,1.3,1:09,10.8,2,1.9,7.7,2,made
1,Brian Roberts,2,Bojan Bogdanovic,6.1,0:14,3.4,0,0.8,28.2,3,missed
2,Brian Roberts,3,Bojan Bogdanovic,0.9,0:00,NaN,3,2.7,10.1,2,missed
3,Brian Roberts,4,Markel Brown,3.4,11:47,10.3,2,1.9,17.2,2,missed
4,Brian Roberts,5,Thaddeus Young,1.1,10:34,10.9,2,2.7,3.7,2,missed

In [120]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128069 entries, 0 to 128068
Data columns (total 11 columns):
Player                       128069 non-null object
Shot Number                  128069 non-null int64
Closest Defender             127680 non-null object
Closest Defender Distance    128069 non-null float64
Game Clock                   128069 non-null object
Shot Clock                   122502 non-null float64
Dribbles                     128069 non-null int64
Touch Time                   128069 non-null float64
Shot Distance                128069 non-null float64
Shot Type                    128069 non-null int64
Shot Result                  128069 non-null object
dtypes: float64(4), int64(3), object(4)
memory usage: 10.7+ MB

In [121]:
new_df['Player'] = new_df['Player'].astype('str')

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [123]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128069 entries, 0 to 128068
Data columns (total 11 columns):
Player                       128069 non-null object
Shot Number                  128069 non-null int64
Closest Defender             127680 non-null object
Closest Defender Distance    128069 non-null float64
Game Clock                   128069 non-null object
Shot Clock                   122502 non-null float64
Dribbles                     128069 non-null int64
Touch Time                   128069 non-null float64
Shot Distance                128069 non-null float64
Shot Type                    128069 non-null int64
Shot Result                  128069 non-null object
dtypes: float64(4), int64(3), object(4)
memory usage: 10.7+ MB